image: Visual Studio 2017
branches:
  only:
    - master

environment:
  matrix:
    - platform: amd64
      qt: msvc2017_64
    - platform: mingw
      qt: mingw530_32

init:
  - if not %platform%==mingw set PATH=C:\Qt\5.12\%qt%\bin;%PATH%

build_script:
  - call version.bat
  - qmake MapleSeed.pro
  - mingw32-make

artifacts:
  - path: bin\*
    name: mapleseed