image: Visual Studio 2017
branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.12.2\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - call version.bat
  - qmake MapleSeed.pro
  - mingw32-make

artifacts:
  - path: bin\*
    name: mapleseed
