image: Visual Studio 2017
branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.12.2\msvc2017_64
  - set MINGW_PATH=C:\Qt\Tools\mingw530_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;C:\Program Files (x86)\MSBuild\12.0\bin\;%MINGW_PATH%\bin;

build_script:
  - call version.bat
  - qmake MapleSeed.pro "CONFIG+=qml_debug"
  - mingw32-make -j8

artifacts:
  - path: bin\*
    name: mapleseed
