image: Visual Studio 2017
branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.12.2\mingw530_32
  - set MINGW_PATH=C:\Qt\Tools\mingw530_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;%MINGW_PATH%\bin;

build_script:
  - call version.bat
  - qmake MapleSeed.pro
  - mingw32-make

artifacts:
  - path: bin\*
    name: mapleseed