image: Visual Studio 2017
branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.12.2\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - call version.bat
  - qmake MapleSeed.pro -spec win32-msvc
  - C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release
  
after_build:
  - cd C:\projects\maple-tree\bin\releases
  - set buildname=build%APPVEYOR_BUILD_NUMBER%_%APPVEYOR_REPO_COMMIT:~0,7%
  - 7z a ..\%buildname%_%name%.zip MapleSeed.exe