image: Visual Studio 2017
branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.12.2\msvc2017_64
  - set PATH=%QTDIR%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;

build_script:
  - call version.bat
  - qmake MapleSeed.pro -spec win32-clang-g++ "CONFIG+=qml_debug"
  - C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
